name: Deployment
on:
  push:
    branches:
      - main
env:
  DATABRICKS_HOST: https://dbc-89c9e463-7ff5.cloud.databricks.com
  DATABRICKS_REPO_ID: "3704530822795613"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: antstackio/databricks-deploy@v1.0.4
        with:
          databricks-repo-branch: 'main'
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}

        